fix compilation error C2864 under VS2010
This is due to the initialization of millimeterToPointMultiplier, which
is not allowed as per the C++ standard but apparently works with gcc. See

http://stackoverflow.com/questions/2454019/why-arent-static-const-floats-allowed